seed: 1234
cuda_device: 0

train_file: "./data/tacred/sample.json"
eval_file: "./data/tacred/sample.json"

model: bert-base-cased
variant: d

max_length: 128
batch_size: 64
lr: 3.e-5
num_epochs: 5
dropout: 0.1
